title: sh1ma.isLand()
author: Kota Amasaka
timezone: Asia/Tokyo
description: おプログラミングなどしていくわよ❣
keywords: プログラミング
# image: pictures/github_icon.png
url: "https://sh1ma.github.io"
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - _bin
  - slides.rb
  - .sass-cache
  - twicache
  - twicard_cache

plugins:
  - jekyll-seo-tag
  - jekyll-target-blank
  - jemoji
  - jekyll-gist
sass:
  style: compressed
markdown: kramdown

encoding: "utf-8"

